name: Output information
on:
  issues:
    types:
      - opened
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Display issue details
        run: |
          echo "A new issue has been opened!"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
